name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: pip install -r requirements.txt
      - run: pip install black isort
      - run: pip install pytest
      - run: black --check .
      - run: isort --check-only .
      - run: npx prettier -c .
      - run: pytest
